version: "3.9"

services:
  api:
    build: .
    container_name: fastapi-demo
    ports:
      - "8000:8000"
    environment:
      MODEL_NAME: ai/qwen3:0.6B-F16
      MODEL_RUNNER_URL: http://model-runner.docker.internal/engines/v1/chat/completions
      PYTHONUNBUFFERED: 1
    volumes:
      - .:/app 
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --log-level info
    networks:
      - api-network
    
    # Optional healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  api-network:
    driver: bridge